editorconfig:
  stage: check
  image: node:latest
  cache:
    paths:
      - node_modules/
  script: |
    if [ ! -f "package.json" ]; then
      npm install eclint
      rm -rf package.json
    fi

    if [ -f ".editorconfig" ]; then
      npx eclint check "{,**/}{,\
    Dockerfile,meson.build,*.{,\
    c,cpp,d,java,scala,json,yml,php}}"
    else
      echo "--> No '.editorconfig' file found, skip."
    fi
  allow_failure: true
